name: wp-museum
recipe: lemp
config:
  webroot: wordpress
  config:
    vhosts: .lando/nginx.conf
services:
  appserver:
    type: php:custom
    overrides:
      build: .lando
      image: wp-museum/wordpress:8.4
      environment:
        XDEBUG_MODE:
        XDEBUG_CONFIG:
        WP_TESTS_PHPUNIT_POLYFILLS_PATH: /app/vendor/yoast/phpunit-polyfills
        WP_TESTS_DIR: /app/tests/
    build_as_root:
      - npm run build
      - /app/.lando/build-wordpress.sh
    config:
      php: .lando/php.ini
  database:
    type: mariadb
    portforward: true
    creds:
      user: wordpress
      password: wordpress
      database: wordpress
  wp-test-server:
    type: php:custom
    via: nginx
    ssl: true
    overrides:
      build: .lando
      image: wp-museum/wordpress:8.4
      environment:
        XDEBUG_MODE:
        XDEBUG_CONFIG:
        WP_TESTS_PHPUNIT_POLYFILLS_PATH: /app/vendor/yoast/phpunit-polyfills
        WP_TESTS_DIR: /app/tests/
        TEST_DB_NAME: wptest
        TEST_DB_USER: wptest
        TEST_DB_PASS: wptest
        TEST_DB_HOST: wp-test-database
        TEST_WP_ADMIN_USER: admin
        TEST_WP_ADMIN_PASS: admin
        TEST_WP_ADMIN_EMAIL: admin@test.com
    build_as_root:
      - /app/.lando/setup-test-wordpress.sh
    run:
      - /app/.lando/reset-test-wordpress.sh
    config:
      php: .lando/php.ini
      vhosts: .lando/nginx-test.conf
  wp-test-database:
    type: mariadb
    portforward: true
    creds:
      user: wptest
      password: wptest
      database: wptest
  playwright:
    type: node:23
    build_as_root:
      - cd /app/tests/playwright && npm install && npx playwright install --with-deps
    overrides:
      environment:
        PLAYWRIGHT_BROWSERS_PATH: /app/tests/playwright/browser-cache
        PLAYWRIGHT_HTML_OPEN: never
        TEST_DB_NAME: wptest
        TEST_DB_USER: wptest
        TEST_DB_PASS: wptest
        TEST_DB_HOST: wp-test-database
        TEST_WP_ADMIN_USER: admin
        TEST_WP_ADMIN_PASS: admin
        TEST_WP_ADMIN_EMAIL: admin@test.com

proxy:
  wp-test-server_nginx:
    - wp-test.lndo.site

tooling:
  wp:
    service: appserver
    description: Runs WP-CLI commands
    cmd: wp
  wpd:
    service: appserver
    description: Runs WP-CLI commands with debug on
    cmd: php -d xdebug.start_with_request=yes /usr/local/bin/wp
  wp-install:
    service: appserver
    description: Installs WordPress with user admin and password admin
    cmd: wp core install --title="WordPress Museum" --admin_user=admin --admin_password=admin --admin_email=admin@example.com --skip-email --url=wp-museum.lndo.site
  phpunit:
    service: wp-test-server
    description: Runs PHPUnit tests
    cmd: phpunit
  phpunit-debug:
    service: wp-test-server
    description: Runs local tests with xdebug
    cmd: php -d xdebug.start_with_request=yes /app/vendor/bin/phpunit
  test-reset:
    service: wp-test-server
    description: Reset test WordPress to clean state
    cmd: /app/.lando/reset-test-wordpress.sh
  test:
    service: wp-test-server
    description: Reset test environment and run PHPUnit tests
    cmd: /app/.lando/reset-test-wordpress.sh && phpunit

  npm:
    service: appserver
    description: Runs npm commands
    cmd: npm
  mysql:
    service: database
    description: Runs MySQL commands
    cmd: mysql -u wordpress -pwordpress wordpress
  playwright:
    description: Runs Playwright tests
    cmd:
      - wp-test-server: /app/.lando/reset-test-wordpress.sh
      - playwright: cd /app/tests/playwright && npx playwright test --reporter=line --max-failures=1
  playwright-html:
    description: Runs Playwright tests with HTML report and videos
    cmd:
      - wp-test-server: /app/.lando/reset-test-wordpress.sh
      - playwright: cd /app/tests/playwright && npx playwright test --reporter=html --max-failures=1
  playwright-multi:
    description: Runs Playwright tests against all browsers (chromium, firefox, webkit) with HTML report
    cmd:
      - wp-test-server: /app/.lando/reset-test-wordpress.sh
      - playwright: cd /app/tests/playwright && npx playwright test --config=playwright.multi-browser.config.js --reporter=html
