name: wp-museum
recipe: lemp
config:
  webroot: wordpress
  config:
    vhosts: .lando/nginx.conf
services:
  appserver:
    type: php:custom
    overrides:
      build: .lando
      image: wp-museum/wordpress:8.4
      environment:
        XDEBUG_MODE:
        XDEBUG_CONFIG:
        WP_TESTS_PHPUNIT_POLYFILLS_PATH: /app/vendor/yoast/phpunit-polyfills
        WP_TESTS_DIR: /app/tests/
    build_as_root:
      - npm run build
      - /app/.lando/build-wordpress.sh
    config:
      php: .lando/php.ini
  database:
    type: mariadb
    portforward: true
    creds:
      user: wordpress
      password: wordpress
      database: wordpress
tooling:
  wp:
    service: appserver
    description: Runs WP-CLI commands
    cmd: wp
  wpd:
    service: appserver
    description: Runs WP-CLI commands with debug on
    cmd: php -d xdebug.start_with_request=yes /usr/local/bin/wp
  wp-install:
    service: appserver
    description: Installs WordPress with user admin and password admin
    cmd: wp core install --title="WordPress Museum" --admin_user=admin --admin_password=admin --admin_email=admin@example.com --skip-email --url=wp-museum.lndo.site
  phpunit:
    service: appserver
    description: Runs PHPUnit tests
    cmd: phpunit
  install-wp-tests:
    service: appserver
    description: Installs the WordPress test suite
    cmd: /app/.lando/install-wp-tests.sh
  npm:
    service: appserver
    description: Runs npm commands
    cmd: npm
  mysql:
    service: database
    description: Runs MySQL commands
    cmd: mysql -u wordpress -pwordpress wordpress
